SalesSys/Models/Sale.cs
namespace SalesSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Sale")]
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            ProductSales = new HashSet<ProductSale>();
        }

        [Key]
        public int IdSale { get; set; }

        public int Amount { get; set; }

        [Column(TypeName = "money")]
        public decimal Value { get; set; }

        public DateTime Date { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSales { get; set; }
    }
}

SalesSys/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalesSys.Models;

namespace SalesSys.Controllers
{
    public class SalesController : Controller
    {
        private ContextDB db = new ContextDB();

        // GET: Sales
        public async Task<ActionResult> Index()
        {
            return View(await db.Sales.ToListAsync());
        }
        
        // GET: Sales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Amount,Value,Date", Exclude="IdSale")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Sales.Add(sale);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sale);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalesSys/Views/Sales/Create.cshtml
@model SalesSys.Models.Sale

<section class="content-header">
    <h1>Register new sale</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-home"></i> @Html.ActionLink("Home", "Index", "Home")</li>
        <li><a href="#">Sale</a></li>
        <li class="active">@Html.ActionLink("Create", "Create", "Sales")</li>
    </ol>
</section>

<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h4>Sale's form</h4>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>

        @using (Html.BeginForm("Create", "Sales", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="box-body">
                @Html.AntiForgeryToken()
                <div class="form-horizontal col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdSale)

                    <div class="row form-group col-md-4">
                        <label class="control-label">Item</label>
                        <div>
                            <input type="text" id="searchProduct" name="searchProduct" placeholder="Search by item code" class="form-control">
                        </div>
                    </div>

                    <div class="row form-group col-md-8">
                        <div>
                            <button type="submit" value="SearchItem" class="btn btn-primary pull-left" style="margin-top:26px;">
                            <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                    <div class="form-group  col-md-12">

                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label" })
                        <div>
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>

                        @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label" })
                        <div>
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
                        </div>

                        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                        <div>
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>

                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" value="Save" class="btn btn-primary pull-right">
                    Register
                </button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-primary pull-left" })
            </div>
        }

    </div>
</section>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    $(function () {
        $('#datepicker').datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true
        });
        $('#price').maskMoney({
            prefix: 'R$ ',
            allowNegative: false,
            thousands: '.',
            decimal: ',',
        });
    });
    </script>
}

SalesSys/Views/Sales/Index.cshtml
@model IEnumerable<SalesSys.Models.Sale>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdSale }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdSale }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdSale })
        </td>
    </tr>
}

</table>